# Generated by Django 4.2.4 on 2023-10-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='favorite_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='services.service'),
        ),
    ]
