# Generated by Django 4.2.4 on 2023-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
