# Generated by Django 4.2.4 on 2023-10-03 10:11

import core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplierprofile",
            old_name="serve_at_customer",
            new_name="customer_place",
        ),
        migrations.RenameField(
            model_name="supplierprofile",
            old_name="serve_at_supplier",
            new_name="supplier_place",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    core.validators.RangeValueValidator(10, 12),
                    users.validators.phone_number_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    core.validators.RangeValueValidator(10, 12),
                    users.validators.phone_number_validator,
                ],
            ),
        ),
    ]
