# Generated by Django 4.2.4 on 2023-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_photo_customerprofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
