# Generated by Django 4.2.4 on 2023-10-05 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0002_rename_serve_at_customer_supplierprofile_customer_place_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="customer_place",
        ),
        migrations.RemoveField(
            model_name="supplierprofile",
            name="supplier_place",
        ),
    ]
