# Generated by Django 4.2.4 on 2023-10-14 10:04

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "__first__"),
        ("users", "0002_customerprofile_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierprofile",
            name="outdoor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.outdoor",
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="specialist_type",
            field=models.CharField(
                choices=[
                    ("cynology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("grooming", "Грумер"),
                ],
                default="cynology",
                max_length=30,
                validators=[core.validators.validate_letters],
                verbose_name="тип услуги",
            ),
            preserve_default=False,
        ),
    ]
