# Generated by Django 4.2.4 on 2023-10-16 08:24

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_supplierprofile_outdoor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="outdoor",
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="about",
            field=models.TextField(
                blank=True,
                max_length=300,
                null=True,
                validators=[core.validators.validate_alphanumeric],
                verbose_name="О себе",
            ),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("cat", "Кошка"),
                    ("dog", "Собака"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                default="cat",
                max_length=30,
                verbose_name="тип животного",
            ),
            preserve_default=False,
        ),
    ]
