# Generated by Django 4.2.4 on 2023-10-07 06:54

import core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_supplierprofile_customer_place_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    core.validators.PhoneNumberValidator(10, 12),
                    users.validators.phone_number_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="phone_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    core.validators.PhoneNumberValidator(10, 12),
                    users.validators.phone_number_validator,
                ],
            ),
        ),
    ]
