# Generated by Django 4.2.4 on 2023-11-15 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customerprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="supplierprofile",
            name="image",
        ),
    ]
