# Generated by Django 4.2.4 on 2023-10-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customerprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
