# Generated by Django 4.2.4 on 2023-11-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customerprofile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
