# Generated by Django 4.2.4 on 2023-11-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_supplierprofile_outdoor_supplierprofile_about_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierprofile",
            name="specialist_type",
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("dog", "Собака"),
                    ("cat", "Кошка"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="тип животного",
            ),
        ),
    ]
