# Generated by Django 4.2.4 on 2023-10-12 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customerprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="first_name",
            field=models.CharField(
                default="djon",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_name",
            field=models.CharField(
                default="smit",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="first_name",
            field=models.CharField(
                default="sdf",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplierprofile",
            name="last_name",
            field=models.CharField(
                default="sdfs",
                max_length=15,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
