# Generated by Django 4.2.4 on 2023-11-15 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customerprofile_image_supplierprofile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="supplierprofile",
            name="image",
        ),
    ]
