# Generated by Django 4.2.4 on 2023-11-03 12:30

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_supplierprofile_specialist_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text=("Enter a strong password.",),
                max_length=128,
                validators=[
                    django.contrib.auth.password_validation.validate_password,
                    django.core.validators.MinLengthValidator(8),
                    django.contrib.auth.password_validation.CommonPasswordValidator,
                ],
                verbose_name=("password",),
            ),
        ),
    ]
