# Generated by Django 4.2.4 on 2023-10-12 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customerprofile_first_name_customerprofile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
