# Generated by Django 4.2.4 on 2023-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customerprofile_image_supplierprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/customers/avatar/"
            ),
        ),
        migrations.AlterField(
            model_name="supplierprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/suppliers/avatar/"
            ),
        ),
    ]
