# Generated by Django 4.2.4 on 2023-10-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=True, verbose_name="Рабочий день"),
                ),
                (
                    "start_work_time",
                    models.TimeField(
                        default="09:00:00", verbose_name="Время начала работы"
                    ),
                ),
                (
                    "end_work_time",
                    models.TimeField(
                        default="19:00:00", verbose_name="Время окончания работы"
                    ),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True,
                        default="13:00:00",
                        null=True,
                        verbose_name="Время начала перерыва",
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True,
                        default="14:00:00",
                        null=True,
                        verbose_name="Время окончания перерыва",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "расписание специалиста",
            },
        ),
    ]
