# Generated by Django 4.2.4 on 2023-10-20 10:05

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutDoor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("out", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "выезд",
                "verbose_name_plural": "выезды",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "tuesday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "wednesday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "thursday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "friday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "saturday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "sunday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
                (
                    "breakTime",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        null=True,
                        size=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "расписание специалиста",
            },
        ),
    ]
