# Generated by Django 4.2.4 on 2023-11-13 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="time_per_visit",
            field=models.IntegerField(
                choices=[
                    (datetime.timedelta(seconds=1800), "0.5 часа"),
                    (datetime.timedelta(seconds=3600), "1 час"),
                    (datetime.timedelta(seconds=5400), "1.5 часа"),
                    (datetime.timedelta(seconds=7200), "2 часа"),
                ],
                default=datetime.timedelta(seconds=1800),
            ),
        ),
    ]
