# Generated by Django 4.2.4 on 2023-10-23 09:56

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_remove_service_cost_from_remove_service_cost_to"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="supplier",
        ),
        migrations.AddField(
            model_name="schedule",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("Пн.", "Понедельник"),
                    ("Вт.", "Вторник"),
                    ("Ср.", "Среда"),
                    ("Чт", "Четверг"),
                    ("Пт.", "Пятница"),
                    ("Сб.", "Суббота"),
                    ("Вс.", "Воскресенье"),
                ],
                verbose_name="День недели",
            ),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=50)),
                (
                    "cost_from",
                    models.DecimalField(
                        decimal_places=0,
                        default=500,
                        max_digits=5,
                        validators=[core.validators.RangeValueValidator(1, 100000)],
                    ),
                ),
                (
                    "cost_to",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000,
                        max_digits=5,
                        validators=[core.validators.RangeValueValidator(1, 100000)],
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
