# Generated by Django 4.2.4 on 2023-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_schedule_time_per_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="time_per_visit",
            field=models.IntegerField(
                choices=[
                    (30, "0.5 часа"),
                    (60, "1 час"),
                    (90, "1.5 часа"),
                    (120, "2 часа"),
                ],
                default=30,
            ),
        ),
    ]
