# Generated by Django 4.2.4 on 2023-10-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_remove_service_cost_from_remove_service_cost_to"),
        ("core", "0003_alter_price_options_price_cost_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="services.service",
            ),
        ),
    ]
