# Generated by Django 4.2.4 on 2023-10-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_remove_service_cost_from_remove_service_cost_to"),
        ("core", "0004_alter_schedule_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="time_per_visit",
            field=models.DecimalField(
                choices=[(0.5, 0.5), (1.0, 1.0), (1.5, 1.5), (2.0, 2.0)],
                decimal_places=1,
                default=0.5,
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="services.service",
            ),
        ),
    ]
