# Generated by Django 4.2.4 on 2023-11-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_customerprofile_image_supplierprofile_image"),
        ("core", "0004_alter_schedule_arround_clock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="break_end_time",
            field=models.TimeField(
                default="12:00:00", verbose_name="Время окончания перерыва"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="break_start_time",
            field=models.TimeField(
                default="11:00:00", verbose_name="Время начала перерыва"
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("Пн", "Понедельник"),
                    ("Вт", "Вторник"),
                    ("Ср", "Среда"),
                    ("Чт", "Четверг"),
                    ("Пт", "Пятница"),
                    ("Сб", "Суббота"),
                    ("Вс", "Воскресенье"),
                ],
                verbose_name="День недели",
            ),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="users.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "слот бронирования",
            },
        ),
    ]
