# Generated by Django 4.2.4 on 2023-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_schedule_time_per_visit_alter_price_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="arround_clock",
            field=models.BooleanField(default=False),
        ),
    ]
