# Generated by Django 4.2.4 on 2023-10-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_schedule_arround_clock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.CharField(
                choices=[
                    ("Пн.", "Понедельник"),
                    ("Вт.", "Вторник"),
                    ("Ср.", "Среда"),
                    ("Чт.", "Четверг"),
                    ("Пт.", "Пятница"),
                    ("Сб.", "Суббота"),
                    ("Вс.", "Воскресенье"),
                ],
                verbose_name="День недели",
            ),
        ),
    ]
