# Generated by Django 4.2.4 on 2023-10-27 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_schedule_weekday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
    ]
