# Generated by Django 4.2.4 on 2023-10-12 19:35

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[core.validators.RangeValueValidator(0, 50)])),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[core.validators.RangeValueValidator(0, 11)])),
            ],
            options={
                'verbose_name': 'возраст питомца',
                'verbose_name_plural': 'возрасты питомцев',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('pig', 'Морская свинка'), ('hom', 'Хомяк'), ('hor', 'Хорек'), ('rab', 'Кролик'), ('ano', 'Другое')], max_length=30, verbose_name='вид животного')),
            ],
            options={
                'verbose_name': 'характеристика животного',
                'verbose_name_plural': 'характеристики животных',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('pig', 'Морская свинка'), ('hom', 'Хомяк'), ('hor', 'Хорек'), ('rab', 'Кролик'), ('ano', 'Другое')], max_length=30, verbose_name='вид животного')),
                ('breed', models.CharField(blank=True, max_length=30, null=True, verbose_name='порода')),
                ('name', models.CharField(max_length=30, verbose_name='имя питомца')),
                ('pet_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.FloatField(validators=[core.validators.RangeValueValidator(0, 200)])),
                ('is_sterilized', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Не знаю', 'Не знаю')], default='Не знаю', max_length=10)),
                ('is_vaccinated', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Не знаю', 'Не знаю')], default='Не знаю', max_length=10)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.age')),
            ],
            options={
                'verbose_name': 'питомец',
                'verbose_name_plural': 'питомцы',
            },
        ),
    ]
