# Generated by Django 4.2.4 on 2023-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="photo",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.CharField(
                choices=[
                    ("Собака", "Собака"),
                    ("Кошка", "Кошка"),
                    ("Морская свинка", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("Собака", "Собака"),
                    ("Кошка", "Кошка"),
                    ("Морская свинка", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
    ]
