# Generated by Django 4.2.4 on 2023-10-05 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Age",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(0)]
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(11)]
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="pet",
            name="unique_name_for_pet",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("name", "breed", "type"), name="unique_name_for_pet"
            ),
        ),
    ]
