# Generated by Django 4.2.4 on 2023-09-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('pig', 'Морская свинка'), ('hom', 'Хомяк'), ('ano', 'Другое')], max_length=30, verbose_name='вид питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(choices=[('1', 'до 5кг.'), ('2', '5 - 10кг.'), ('3', '10 - 20кг.'), ('4', 'более 20кг.')], max_length=10),
        ),
    ]
