# Generated by Django 4.2.4 on 2023-09-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=255, verbose_name="имя питомца"),
        ),
    ]
