# Generated by Django 4.2.4 on 2023-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_photo_pet_image_alter_animal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="is_sterilized",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="is_vaccinated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
