# Generated by Django 4.2.4 on 2023-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.CharField(
                choices=[
                    ("cat", "Кошка"),
                    ("dog", "Собака"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("cat", "Кошка"),
                    ("dog", "Собака"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
    ]
