# Generated by Django 4.2.4 on 2023-10-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_age_remove_pet_unique_name_for_pet_remove_pet_age_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pet",
            name="unique_name_for_pet",
        ),
        migrations.AddField(
            model_name="pet",
            name="age",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pets.age",
            ),
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("name", "breed", "age", "type"), name="unique_name_for_pet"
            ),
        ),
    ]
