# Generated by Django 4.2.4 on 2023-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('pets', '0002_alter_pet_type_alter_pet_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='users.customerprofile', verbose_name='владелец питомца'),
        ),
    ]
