# Generated by Django 4.2.4 on 2023-09-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cat", "Кошка"),
                            ("dog", "Собака"),
                            ("pig", "Морская свинка"),
                            ("hom", "Хомяк"),
                            ("ano", "Другое"),
                        ],
                        max_length=30,
                        verbose_name="вид животного",
                    ),
                ),
            ],
            options={
                "verbose_name": "характеристика животного",
                "verbose_name_plural": "характеристики животных",
            },
        ),
        migrations.RemoveField(
            model_name="pet",
            name="id",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="type",
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=30, verbose_name="имя питомца"),
        ),
        migrations.AddField(
            model_name="pet",
            name="animal_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="pets.animal",
            ),
            preserve_default=False,
        ),
    ]
