# Generated by Django 4.2.4 on 2023-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_alter_pet_is_sterilized_alter_pet_is_vaccinated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="type",
            field=models.CharField(
                choices=[
                    ("Собака", "Собака"),
                    ("Кошка", "Кошка"),
                    ("Морская свинка", "Морская свинка"),
                    ("Хомяк", "Хомяк"),
                    ("Хорек", "Хорек"),
                    ("Кролик", "Кролик"),
                    ("Другое", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("Собака", "Собака"),
                    ("Кошка", "Кошка"),
                    ("Морская свинка", "Морская свинка"),
                    ("Хомяк", "Хомяк"),
                    ("Хорек", "Хорек"),
                    ("Кролик", "Кролик"),
                    ("Другое", "Другое"),
                ],
                max_length=30,
                verbose_name="вид животного",
            ),
        ),
    ]
