# Generated by Django 4.2.4 on 2023-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_animal_remove_pet_id_remove_pet_type_alter_pet_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="animal_ptr",
        ),
        migrations.AddField(
            model_name="pet",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[
                    ("cat", "Кошка"),
                    ("dog", "Собака"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("ano", "Другое"),
                ],
                default="dog",
                max_length=30,
                verbose_name="вид животного",
            ),
            preserve_default=False,
        ),
    ]
