# Generated by Django 4.2.4 on 2023-10-07 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_remove_pet_unique_name_for_pet_pet_age_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="age",
            options={
                "verbose_name": "возраст питомца",
                "verbose_name_plural": "возрасты питомцев",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="age",
            name="year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MaxValueValidator(50)]
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="is_sterilized",
            field=models.CharField(
                choices=[("Да", "Да"), ("Нет", "Нет"), ("Не знаю", "Не знаю")],
                default="Не знаю",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="is_vaccinated",
            field=models.CharField(
                choices=[("Да", "Да"), ("Нет", "Нет"), ("Не знаю", "Не знаю")],
                default="Не знаю",
                max_length=10,
            ),
        ),
    ]
