# Generated by Django 4.2.4 on 2023-10-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_alter_age_options_pet_pet_photo_alter_age_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pets",
                to="pets.age",
            ),
        ),
    ]
