# Generated by Django 4.2.4 on 2023-10-07 08:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_alter_pet_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.FloatField(
                validators=[core.validators.RangeValueValidator(0, 200)]
            ),
        ),
    ]
