# Generated by Django 4.2.4 on 2023-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0006_pet_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pets/avatar/"),
        ),
    ]
