# Generated by Django 4.2.4 on 2023-10-07 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0006_alter_pet_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="age",
            name="month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(11)],
            ),
        ),
        migrations.AlterField(
            model_name="age",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(50)],
            ),
        ),
        migrations.AddConstraint(
            model_name="age",
            constraint=models.CheckConstraint(
                check=models.Q(("year__gt", 0), ("month__gt", 0), _connector="OR"),
                name="year_or_month_not_zero",
            ),
        ),
    ]
