# Generated by Django 4.2.4 on 2023-10-12 08:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_alter_age_month_alter_age_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="age",
            name="month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[core.validators.RangeValueValidator(0, 11)],
            ),
        ),
        migrations.AlterField(
            model_name="age",
            name="year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[core.validators.RangeValueValidator(0, 50)],
            ),
        ),
    ]
