# Generated by Django 4.2.4 on 2023-10-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customerprofile_first_name_customerprofile_last_name_and_more"),
        ("pets", "0008_alter_age_month_alter_age_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet",
                to="users.customerprofile",
                verbose_name="владелец питомца",
            ),
        ),
    ]
