# Generated by Django 4.2.4 on 2023-09-30 20:17

import core.utils
import core.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_supplierprofile_serve_at_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[core.validators.validate_service_name], verbose_name='название услуги')),
                ('service_type', models.CharField(choices=[('cynology', 'Кинолог'), ('veterenary', 'Ветеринар'), ('shelter', 'Зооняня'), ('grooming', 'Грумер')], max_length=30, validators=[core.validators.validate_letters], verbose_name='тип услуги')),
                ('pet_type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('pig', 'Морская свинка'), ('hom', 'Хомяк'), ('ano', 'Другое')], default='dog', max_length=30, verbose_name='тип животного')),
                ('price', models.PositiveSmallIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(100000, 'Введите корректный возраст!')], verbose_name='Цена за услугу')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(600, 'Не корректная продолжительность.')], verbose_name='Продолжительность услуги в минутах')),
                ('work_time_from', models.TimeField(default='00:00:00', verbose_name='От')),
                ('work_time_to', models.TimeField(default='23:59:59', verbose_name='До')),
                ('format', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('i', 'Индивидуальные занятия'), ('m', 'Занятия в мини-группе'), ('g', 'Групповые занятия'), ('d', 'Дрессировка с передержкой у кинолога'), ('n', 'Другое')], max_length=50, validators=[core.validators.validate_letters]), blank=True, null=True, size=None)),
                ('task', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('correction', 'Коррекция проблемного поведения'), ('etraining', 'Воспитательная дрессировка щенка'), ('education', 'Обучение командам'), ('training', 'Дрессировка служебных/ охотничьих собак, подготовка к экзамену ОКД'), ('sport', 'Спортивная дрессировка'), ('adapt', 'Адаптация собаки из приюта'), ('prep', 'Подготовка к участию на выставке'), ('consult', 'Консультация'), ('another', 'Другое')], max_length=50), blank=True, default=core.utils.cynology_type_default, null=True, size=None)),
                ('grooming_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Hygienic', 'Hygienic'), ('Exhibition', 'Exhibition'), ('Decorative', 'Decorative'), ('ych', 'You can choose')], max_length=20, validators=[core.validators.validate_letters]), blank=True, default=core.utils.grooming_type_default, null=True, size=None)),
                ('about', models.TextField(blank=True, max_length=300, null=True, validators=[core.validators.validate_alphanumeric], verbose_name='О себе')),
                ('published', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplierprofile')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[core.validators.validate_service_name], verbose_name='название услуги')),
                ('service_type', models.CharField(choices=[('cynology', 'Кинолог'), ('veterenary', 'Ветеринар'), ('shelter', 'Зооняня'), ('grooming', 'Грумер')], max_length=30, validators=[core.validators.validate_letters], verbose_name='тип услуги')),
                ('favour', models.CharField(choices=[('cynology', 'Кинолог'), ('veterenary', 'Ветеринар'), ('shelter', 'Зооняня'), ('grooming', 'Грумер')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=300)),
                ('confirmed', models.BooleanField(default=False, verbose_name='подтверждено или нет')),
                ('actual', models.BooleanField(default=False, verbose_name='активно или нет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplierprofile')),
            ],
            options={
                'verbose_name': 'бронь услуги',
                'verbose_name_plural': 'брони услуг',
            },
        ),
    ]
