# Generated by Django 4.2.4 on 2023-10-16 11:07

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0004_remove_supplierprofile_outdoor_supplierprofile_about_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[core.validators.validate_alphanumeric],
                        verbose_name="название услуги",
                    ),
                ),
                ("customer_place", models.BooleanField(default=False)),
                ("supplier_place", models.BooleanField(default=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "услуги",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[core.validators.validate_alphanumeric],
                        verbose_name="название услуги",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "to_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        validators=[core.validators.validate_current_and_future_month],
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[core.validators.validate_alphanumeric],
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False, verbose_name="подтверждено или нет"
                    ),
                ),
                (
                    "actual",
                    models.BooleanField(default=False, verbose_name="активно или нет"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customerprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_services",
                        to="services.service",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронь услуги",
                "verbose_name_plural": "брони услуг",
            },
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="unique_for_services"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_from__lte", models.F("cost_to"))),
                name="cost_range",
            ),
        ),
    ]
