# Generated by Django 4.2.4 on 2023-09-30 06:56

import core.utils
import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingservice",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="name",
            field=models.CharField(
                choices=[
                    ("Synology", "Кинолог"),
                    ("Veterenary", "Ветеринар"),
                    ("Shelter", "Зооняня"),
                    ("groomer", "Грумер"),
                ],
                max_length=30,
                validators=[core.validators.validate_letters],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    ("Synology", "Кинолог"),
                    ("Veterenary", "Ветеринар"),
                    ("Shelter", "Зооняня"),
                    ("groomer", "Грумер"),
                ],
                max_length=30,
                validators=[core.validators.validate_letters],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="task",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("correction", "Коррекция проблемного поведения"),
                        ("etraining", "Воспитательная дрессировка щенка"),
                        ("education", "Обучение командам"),
                        (
                            "training",
                            "Дрессировка служебных/ охотничьих собак, подготовка к экзамену ОКД",
                        ),
                        ("sport", "Спортивная дрессировка"),
                        ("adapt", "Адаптация собаки из приюта"),
                        ("prep", "Подготовка к участию на выставке"),
                        ("consult", "Консультация"),
                        ("another", "Другое"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=core.utils.synology_type_default,
                null=True,
                size=None,
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="unique_for_services"
            ),
        ),
    ]
