# Generated by Django 4.2.4 on 2023-10-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="supplier",
        ),
        migrations.AddField(
            model_name="service",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="users.supplierprofile",
                verbose_name="исполнитель",
            ),
            preserve_default=False,
        ),
    ]
