# Generated by Django 4.2.4 on 2023-11-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="users.supplierprofile",
                verbose_name="исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="users.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="customer",
            field=models.ManyToManyField(
                related_name="prices",
                through="services.Booking",
                to="users.customerprofile",
                verbose_name="клиенты",
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="favoritearticles",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_articles",
                to="users.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_favorites",
                to="users.customerprofile",
                verbose_name="заказчик",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_favorites",
                to="services.service",
                verbose_name="понравившиеся услуги",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.customerprofile",
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.price",
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_from__lte", models.F("cost_to"))),
                name="cost_range",
            ),
        ),
    ]
