# Generated by Django 4.2.4 on 2023-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_remove_service_supplier_service_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="extra_fields",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
