# Generated by Django 4.2.4 on 2023-10-02 15:01

import core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="to_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[core.validators.validate_current_and_future_month],
            ),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="favour",
            field=models.CharField(
                choices=[
                    ("cynology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("grooming", "Грумер"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="place",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                validators=[core.validators.validate_alphanumeric],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[core.validators.RangeValueValidator(1, 650)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.PositiveSmallIntegerField(
                default=500,
                validators=[core.validators.RangeValueValidator(1, 100000)],
                verbose_name="Цена за услугу",
            ),
        ),
    ]
