# Generated by Django 4.2.4 on 2023-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="time_per_visit",
            field=models.IntegerField(
                choices=[
                    (30, "0.5 часа"),
                    (60, "1 час"),
                    (90, "1.5 часа"),
                    (120, "2 часа"),
                ],
                default=30,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/suppliers/advertisement/"
            ),
        ),
    ]
