# Generated by Django 4.2.4 on 2023-09-30 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_service_pet_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
    ]
