# Generated by Django 4.2.4 on 2023-10-02 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0003_bookingservice_to_date_alter_bookingservice_favour_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingservice",
            old_name="client",
            new_name="customer",
        ),
    ]
