# Generated by Django 4.2.4 on 2023-10-21 09:22

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_service_extra_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(
                max_length=20, validators=[core.validators.validate_alphanumeric]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                max_length=20, validators=[core.validators.validate_alphanumeric]
            ),
        ),
    ]
