# Generated by Django 4.2.4 on 2023-10-03 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_rename_client_bookingservice_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingservice",
            old_name="confirmed",
            new_name="is_done",
        ),
    ]
