# Generated by Django 4.2.4 on 2023-10-21 10:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_alter_booking_name_alter_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(
                default="shelter",
                max_length=50,
                validators=[core.validators.validate_alphanumeric],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                default="shelter",
                max_length=50,
                validators=[core.validators.validate_alphanumeric],
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="unique_name_for_service"
            ),
        ),
    ]
