# Generated by Django 4.2.4 on 2023-09-30 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_bookingservice_name_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
    ]
