# Generated by Django 4.2.4 on 2023-10-03 14:08

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_rename_confirmed_bookingservice_is_done"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookingservice",
            old_name="service_type",
            new_name="specialist_type",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="service_type",
            new_name="specialist_type",
        ),
        migrations.AddField(
            model_name="service",
            name="vet_services",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("consultation", "Консультации"),
                        ("veterinary", "Диагностика заболевания и лечение"),
                        ("injection", "Введение инъекций"),
                        ("vaccinating", "Вакцинация"),
                        ("sterializing", "Стерилизация"),
                        ("vetpassport", "Оформление ветпаспорта"),
                        ("sleeping", "Усыпление"),
                        ("another", "Другое"),
                    ],
                    max_length=30,
                    validators=[core.validators.validate_letters],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="grooming_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Hygienic", "Hygienic"),
                        ("Exhibition", "Exhibition"),
                        ("Decorative", "Decorative"),
                        ("ych", "You can choose"),
                    ],
                    max_length=30,
                    validators=[core.validators.validate_letters],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("cat", "Кошка"),
                    ("dog", "Собака"),
                    ("pig", "Морская свинка"),
                    ("hom", "Хомяк"),
                    ("hor", "Хорек"),
                    ("rab", "Кролик"),
                    ("ano", "Другое"),
                ],
                max_length=30,
                verbose_name="тип животного",
            ),
        ),
    ]
