# Generated by Django 4.2.4 on 2023-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_favorite_services_favorite_услуга_уже_в_избранном"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favoritearticles",
            constraint=models.UniqueConstraint(
                fields=("article_id", "customer"),
                name="services_favoritearticles статья уже в избранном",
            ),
        ),
    ]
