# Generated by Django 4.2.4 on 2023-10-04 08:13

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0006_rename_service_type_bookingservice_specialist_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "tuesday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "wednesday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "thursday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "friday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "saturday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
                (
                    "sunday_hours",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            validators=[core.validators.RangeValueValidator(0, 24)]
                        ),
                        size=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "расписание специалиста",
            },
        ),
    ]
