# Generated by Django 4.2.4 on 2023-10-21 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_booking_name_alter_service_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="service",
            name="unique_name_for_service",
        ),
    ]
