# Generated by Django 4.2.4 on 2023-10-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="work_time_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="work_time_to",
        ),
        migrations.AddField(
            model_name="service",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.schedule",
            ),
        ),
    ]
