# Generated by Django 4.2.4 on 2023-09-30 09:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_bookingservice_name_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingservice",
            name="favour",
            field=models.CharField(
                choices=[
                    ("synology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("groomer", "Грумер"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="name",
            field=models.CharField(
                choices=[
                    ("synology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("groomer", "Грумер"),
                ],
                max_length=30,
                validators=[core.validators.validate_letters],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    ("synology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("groomer", "Грумер"),
                ],
                max_length=30,
                validators=[core.validators.validate_letters],
            ),
        ),
    ]
