# Generated by Django 4.2.4 on 2023-10-23 06:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_remove_service_unique_name_for_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.AddField(
            model_name="booking",
            name="ad_title",
            field=models.CharField(
                default="заголовок услуги",
                max_length=50,
                validators=[core.validators.validate_alphanumeric],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="ad_title",
            field=models.CharField(
                default="Заголовок услуги",
                max_length=50,
                validators=[core.validators.validate_alphanumeric],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(default="Описание", max_length=50),
            preserve_default=False,
        ),
    ]
