# Generated by Django 4.2.4 on 2023-10-04 08:43

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_remove_service_work_time_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="friday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="monday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="saturday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="sunday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="thursday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="tuesday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="wednesday_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
    ]
