# Generated by Django 4.2.4 on 2023-09-30 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0008_alter_bookingservice_favour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="task",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
