# Generated by Django 4.2.4 on 2023-10-23 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="cost_from",
        ),
        migrations.RemoveField(
            model_name="service",
            name="cost_to",
        ),
    ]
