# Generated by Django 4.2.4 on 2023-09-30 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_alter_service_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="format",
            new_name="formats",
        ),
    ]
