# Generated by Django 4.2.4 on 2023-10-04 09:30

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_alter_schedule_friday_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="breakTime",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(
                    validators=[core.validators.RangeValueValidator(0, 24)]
                ),
                null=True,
                size=2,
            ),
        ),
    ]
