# Generated by Django 4.2.4 on 2023-09-30 12:27

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_rename_format_service_formats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="formats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("individusl", "Индивидуальные занятия"),
                        ("minigroup", "Занятия в мини-группе"),
                        ("group", "Групповые занятия"),
                        ("training", "Дрессировка с передержкой у кинолога"),
                        ("another", "Другое"),
                    ],
                    max_length=50,
                    validators=[core.validators.validate_letters],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="grooming_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Hygienic", "Hygienic"),
                        ("Exhibition", "Exhibition"),
                        ("Decorative", "Decorative"),
                        ("ych", "You can choose"),
                    ],
                    max_length=20,
                    validators=[core.validators.validate_letters],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
