# Generated by Django 4.2.4 on 2023-10-05 08:12

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_schedule_breaktime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("correction", "Коррекция проблемного поведения"),
                            ("etraining", "Воспитательная дрессировка щенка"),
                            ("education", "Обучение командам"),
                            (
                                "training",
                                "Дрессировка служебных/ охотничьих собак, подготовка к экзамену ОКД",
                            ),
                            ("sport", "Спортивная дрессировка"),
                            ("adapt", "Адаптация собаки из приюта"),
                            ("prep", "Подготовка к участию на выставке"),
                            ("consult", "Консультация"),
                            ("another", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        validators=[core.validators.RangeValueValidator(1, 100000)]
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "прайс",
                "verbose_name_plural": "прайсы",
            },
        ),
    ]
