# Generated by Django 4.2.4 on 2023-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_remove_service_cost_from_remove_service_cost_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
