# Generated by Django 4.2.4 on 2023-10-05 08:43

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models

from services.models import default_price


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0011_remove_service_price_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[core.validators.RangeValueValidator(1, 100000)]
                ),
                default=default_price,
                size=None,
            ),
            preserve_default=False,
        ),
    ]
