# Generated by Django 4.2.4 on 2023-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0011_service_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_for_services",
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="unique_for_booking",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="supplier",
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_done",
            field=models.BooleanField(default=False, verbose_name="окончено или нет"),
        ),
    ]
