# Generated by Django 4.2.4 on 2023-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0012_remove_booking_unique_for_services_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="ad_title",
        ),
        migrations.AddField(
            model_name="booking",
            name="description",
            field=models.TextField(default="0", max_length=1000),
            preserve_default=False,
        ),
    ]
