# Generated by Django 4.2.4 on 2023-10-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("services", "0013_remove_booking_ad_title_booking_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="customer",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="services",
                through="services.Booking",
                to="users.customerprofile",
                verbose_name="клиенты",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.service",
            ),
        ),
    ]
