# Generated by Django 4.2.4 on 2023-10-05 09:24

import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0013_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[core.validators.RangeValueValidator(1, 100000)]
                ),
                default=[1000, 2000],
                size=None,
            ),
        ),
    ]
