# Generated by Django 4.2.4 on 2023-10-05 10:12

import core.utils
import core.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0014_alter_service_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="customer_place",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="supplier_place",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[core.validators.RangeValueValidator(1, 100000)]
                ),
                default=core.utils.default_price,
                size=None,
            ),
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
