# Generated by Django 4.2.4 on 2023-10-27 13:27

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("services", "0014_service_customer_alter_booking_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="service",
        ),
        migrations.RemoveField(
            model_name="service",
            name="customer",
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=50)),
                (
                    "cost_from",
                    models.DecimalField(
                        decimal_places=0,
                        default=500,
                        max_digits=5,
                        validators=[core.validators.RangeValueValidator(1, 100000)],
                    ),
                ),
                (
                    "cost_to",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000,
                        max_digits=5,
                        validators=[core.validators.RangeValueValidator(1, 100000)],
                    ),
                ),
                (
                    "customer",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="prices",
                        through="services.Booking",
                        to="users.customerprofile",
                        verbose_name="клиенты",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.price",
            ),
            preserve_default=False,
        ),
    ]
