# Generated by Django 4.2.4 on 2023-10-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "services",
            "0015_remove_booking_service_remove_service_customer_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={
                "verbose_name": "стоимость услуги",
                "verbose_name_plural": "стоимости услуг",
            },
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                check=models.Q(("cost_from__lte", models.F("cost_to"))),
                name="cost_range",
            ),
        ),
    ]
