# Generated by Django 4.2.4 on 2023-10-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0015_bookingservice_customer_place_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="favour",
        ),
        migrations.AddField(
            model_name="bookingservice",
            name="service",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_services",
                to="services.service",
            ),
            preserve_default=False,
        ),
    ]
