# Generated by Django 4.2.4 on 2023-10-05 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0016_remove_bookingservice_favour_bookingservice_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="about",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="service",
            name="formats",
        ),
        migrations.RemoveField(
            model_name="service",
            name="grooming_type",
        ),
        migrations.RemoveField(
            model_name="service",
            name="task",
        ),
        migrations.RemoveField(
            model_name="service",
            name="vet_services",
        ),
    ]
