# Generated by Django 4.2.4 on 2023-10-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_alter_booking_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="services.price",
            ),
        ),
    ]
