# Generated by Django 4.2.4 on 2023-10-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_alter_age_month_alter_age_year_and_more"),
        ("services", "0017_rename_about_service_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="pet",
            field=models.ForeignKey(
                default=30, on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
            preserve_default=False,
        ),
    ]
