# Generated by Django 4.2.4 on 2023-10-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("services", "0018_alter_booking_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="customer",
            field=models.ManyToManyField(
                related_name="prices",
                through="services.Booking",
                to="users.customerprofile",
                verbose_name="клиенты",
            ),
        ),
    ]
