# Generated by Django 4.2.4 on 2023-10-09 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_bookingservice_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="service",
        ),
        migrations.AddField(
            model_name="service",
            name="booking",
            field=models.ForeignKey(
                default=41,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_services",
                to="services.bookingservice",
            ),
            preserve_default=False,
        ),
    ]
