# Generated by Django 4.2.4 on 2023-10-09 13:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_remove_bookingservice_service_service_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingservice",
            name="specialist_type",
        ),
        migrations.AlterField(
            model_name="service",
            name="specialist_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cynology", "Кинолог"),
                    ("veterenary", "Ветеринар"),
                    ("shelter", "Зооняня"),
                    ("grooming", "Грумер"),
                ],
                max_length=30,
                null=True,
                validators=[core.validators.validate_letters],
                verbose_name="тип услуги",
            ),
        ),
    ]
