# Generated by Django 4.2.4 on 2023-10-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_alter_price_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.price"
            ),
        ),
    ]
