# Generated by Django 4.2.4 on 2023-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0020_alter_booking_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активно или нет"),
        ),
    ]
