# Generated by Django 4.2.4 on 2023-10-09 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_alter_age_month_alter_age_year_and_more"),
        ("users", "0004_alter_customerprofile_phone_number_and_more"),
        ("services", "0021_remove_service_unique_for_services_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookingService",
            new_name="Booking",
        ),
    ]
