# Generated by Django 4.2.4 on 2023-10-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_rename_bookingservice_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_services",
                to="services.booking",
            ),
        ),
    ]
