# Generated by Django 4.2.4 on 2023-10-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0022_alter_booking_price_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="price",
        ),
        migrations.AddField(
            model_name="review",
            name="service",
            field=models.ForeignKey(
                default=104,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="services.service",
            ),
            preserve_default=False,
        ),
    ]
