# Generated by Django 4.2.4 on 2023-11-01 11:31

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0023_remove_review_price_review_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="отменено или нет"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="to_date",
            field=models.DateTimeField(
                default=core.utils.default_booking_time,
                validators=[core.validators.validate_current_and_future_month],
            ),
        ),
    ]
