# Generated by Django 4.2.4 on 2023-11-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        ("services", "0024_booking_is_cancelled_alter_booking_to_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата добавления"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_favorites",
                        to="users.customerprofile",
                        verbose_name="заказчик",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_favorites",
                        to="services.price",
                        verbose_name="понравившиеся услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранная услуга",
                "verbose_name_plural": "избранные услуги",
            },
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("price", "customer"),
                name="services_favorite услуга уже в избранном",
            ),
        ),
    ]
