# Generated by Django 4.2.4 on 2023-11-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0025_favorite_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="services_favorite услуга уже в избранном",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="price",
        ),
        migrations.AddField(
            model_name="favorite",
            name="service",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_favorites",
                to="services.service",
                verbose_name="понравившиеся услуги",
            ),
            preserve_default=False,
        ),
    ]
