# Generated by Django 4.2.4 on 2023-11-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "__first__"),
        (
            "services",
            "0026_remove_favorite_services_favorite_услуга_уже_в_избранном_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата добавления"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_articles",
                        to="users.customerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранные статьи",
                "verbose_name_plural": "избранные статьи",
            },
        ),
    ]
