# Generated by Django 4.2.4 on 2023-11-02 16:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_favoritearticles"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritearticles",
            name="article_id",
            field=models.PositiveIntegerField(
                default=1, validators=[core.validators.RangeValueValidator(1, 6)]
            ),
            preserve_default=False,
        ),
    ]
