# Generated by Django 4.2.4 on 2023-10-12 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'товар в списке покупок',
                'verbose_name_plural': 'товары в списке покупок',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'избранный товар',
                'verbose_name_plural': 'избранные товары',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(choices=[('any', 'For any age'), ('0-11', '0-1'), ('1-3', '1-3'), ('4-10', '4-10'), ('11-20', '11-20'), ('21-30', '21-30')], max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1, 'Введите корректную цену.'), django.core.validators.MaxValueValidator(100000, 'Введите корректную цену.')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/goods/')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', 'Корм и лакомства'), ('toys', 'Игрушки и амуниция'), ('toilet', 'Для туалета'), ('hygiene', 'Гигиена и уход'), ('bowls', 'Миски, лежанки, домики'), ('vetaptheca', 'Ветаптека')], max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
