# Generated by Django 4.2.4 on 2023-11-01 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0002_pet_photo"),
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("food", "Корм и лакомства"),
                            ("toys", "Игрушки и амуниция"),
                            ("toilet", "Для туалета"),
                            ("hygiene", "Гигиена и уход"),
                            ("bowls", "Миски, лежанки, домики"),
                            ("vetaptheca", "Ветаптека"),
                        ],
                        max_length=30,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("any", "For any age"),
                            ("0-11", "0-1"),
                            ("1-3", "1-3"),
                            ("4-10", "4-10"),
                            ("11-20", "11-20"),
                            ("21-30", "21-30"),
                        ],
                        max_length=10,
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Введите корректную цену."
                            ),
                            django.core.validators.MaxValueValidator(
                                100000, "Введите корректную цену."
                            ),
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/goods/"),
                ),
                (
                    "animal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pets.animal"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodscategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата добавления"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_favorites",
                        to="goods.goods",
                        verbose_name="понравившиеся товары",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="users.customerprofile",
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "избранный товар",
                "verbose_name_plural": "избранные товары",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart",
                        to="goods.goods",
                        verbose_name="товары в списке покупок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец списка",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар в списке покупок",
                "verbose_name_plural": "товары в списке покупок",
            },
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("goods", "user"), name="goods_favorite товар уже в избранном"
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("goods", "user"), name="goods_cart товар уже в корзине"
            ),
        ),
    ]
