# Generated by Django 4.2.4 on 2023-10-08 18:29

import authentication.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=authentication.models.create_code, max_length=5, validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
