# Generated by Django 4.2.4 on 2023-10-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcode',
            old_name='users',
            new_name='user',
        ),
    ]
