# Generated by Django 4.2.4 on 2023-10-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_users_emailcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcode',
            name='email',
            field=models.EmailField(default='test@purrfect-care.ru', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
