# Generated by Django 4.2.4 on 2023-10-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_emailcode_user_emailcode_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
